import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

interface CopilotRequest {
  mode: "DEMO" | "ACTIVE_EVENT" | "PLANNING" | "POST_EVENT_REVIEW";
  user_message: string;
  context_packet: Record<string, unknown>;
  retrieved_knowledge: string[];
  constraints: string[];
}

interface CopilotResponse {
  mode_banner: string;
  framing_line?: string;
  insights: string[];
  tradeoffs?: string[];
  source_notes?: string[];
  disclaimer: string;
}

function generateMockResponse(request: CopilotRequest): CopilotResponse {
  const { mode, user_message, context_packet } = request;

  const modeBanners: Record<string, string> = {
    DEMO: "🎯 Demo Mode — Showcasing Copilot Capabilities",
    ACTIVE_EVENT: "🔴 Active Event — Real-time Operational Support",
    PLANNING: "📋 Planning Mode — Strategic Scenario Development",
    POST_EVENT_REVIEW: "📊 Post-Event Review — Analysis & Lessons Learned",
  };

  const modeFramingLines: Record<string, string> = {
    DEMO: "This is a demonstration of the Operator Copilot's analytical capabilities.",
    ACTIVE_EVENT: "Monitoring live scenario conditions and providing real-time guidance.",
    PLANNING: "Helping you prepare and optimize your scenario execution plan.",
    POST_EVENT_REVIEW: "Analyzing completed scenario data to extract actionable insights.",
  };

  const baseInsights = [
    `Analyzing your request: "${user_message.slice(0, 50)}${user_message.length > 50 ? '...' : ''}"`,
  ];

  // Mode-specific insights
  const modeInsights: Record<string, string[]> = {
    DEMO: [
      "The Copilot can process scenario context, operator roles, and lifecycle stages",
      "Integration with knowledge bases enables context-aware recommendations",
      "Real-time validation checks ensure operational readiness",
    ],
    ACTIVE_EVENT: [
      "Current scenario status indicators are being monitored",
      "Operator positioning and resource allocation tracked in real-time",
      "Escalation pathways are primed for rapid response if needed",
    ],
    PLANNING: [
      "Scenario timeline analysis suggests optimal preparation windows",
      "Resource requirements have been mapped against available capacity",
      "Risk factors identified for mitigation planning",
    ],
    POST_EVENT_REVIEW: [
      "Timeline reconstruction shows key decision points",
      "Performance metrics indicate areas for improvement",
      "Lessons learned have been catalogued for future reference",
    ],
  };

  const modeTradeoffs: Record<string, string[]> = {
    DEMO: [
      "Demo mode provides simulated responses only",
      "Full AI integration available in production deployment",
    ],
    ACTIVE_EVENT: [
      "Speed vs. thoroughness: Prioritizing rapid response",
      "Automation vs. human oversight: Maintaining operator control",
    ],
    PLANNING: [
      "Comprehensive planning requires time investment upfront",
      "Flexible plans may sacrifice optimization for adaptability",
    ],
    POST_EVENT_REVIEW: [
      "Deep analysis takes time but yields better insights",
      "Historical data quality affects recommendation accuracy",
    ],
  };

  const contextInsight = context_packet?.scenario_name
    ? `Context loaded for scenario: "${context_packet.scenario_name}"`
    : "No specific scenario context provided";

  return {
    mode_banner: modeBanners[mode] || modeBanners.DEMO,
    framing_line: modeFramingLines[mode],
    insights: [...baseInsights, contextInsight, ...modeInsights[mode]],
    tradeoffs: modeTradeoffs[mode],
    source_notes: [
      "Mock response generated for demonstration purposes",
      "Knowledge retrieval system: Simulated",
      `Constraints applied: ${request.constraints.length || 0}`,
    ],
    disclaimer: "This is a mocked response. In production, responses will be generated by the AI model with real-time data integration.",
  };
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    if (req.method !== 'POST') {
      return new Response(
        JSON.stringify({ error: 'Method not allowed' }),
        { status: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const body: CopilotRequest = await req.json();

    // Validate required fields
    if (!body.mode || !body.user_message) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: mode and user_message are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate mode
    const validModes = ["DEMO", "ACTIVE_EVENT", "PLANNING", "POST_EVENT_REVIEW"];
    if (!validModes.includes(body.mode)) {
      return new Response(
        JSON.stringify({ error: `Invalid mode. Must be one of: ${validModes.join(', ')}` }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Generate mock response
    const response = generateMockResponse(body);

    return new Response(
      JSON.stringify(response),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error processing copilot request:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
